language: rust
os: linux
dist: xenial

cache:
  - cargo

rust:
  - stable

before_install:
  # 确保安装最新的 Ruby 版本（修复 dpl 安装问题）
  - rvm install 2.7
  - rvm use 2.7 --default
  # 安装兼容的 json_pure 版本（如果需要）
  - gem install json_pure -v 2.7.6

before_script:
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/mdbook || cargo install mdbook)
  - cargo install-update -a

script:
  - cd ./book
  - mdbook build # 如果有自定义路径：mdbook build path/to/mybook && mdbook test path/to/mybook

deploy:
  provider: pages
  strategy: git
  edge: true
  cleanup: false
  github-token: $GITHUB_TOKEN
  local-dir: ./book/target # 修改为 mdbook 默认生成的输出路径
  keep-history: false
  on:
    branch: main
  target_branch: gh-pages
