language: rust
os: linux
dist: xenial

cache:
  - cargo

rust:
  - stable

before_install:
  # 安装新版本的 Ruby
  - rvm install 2.7.5
  - rvm use 2.7.5 --default
  # 手动安装 json_pure 和 dpl
  - gem install json_pure -v 2.7.6
  - gem install dpl --pre

before_script:
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/mdbook || cargo install mdbook)
  - cargo install-update -a

script:
  - cd ./book
  - mdbook build # 如果有自定义路径：mdbook build path/to/mybook && mdbook test path/to/mybook

deploy:
  provider: pages
  strategy: git
  edge: true
  cleanup: false
  github-token: $GITHUB_TOKEN
  local-dir: ./book/book # 指向 mdbook 默认生成的输出路径
  keep-history: false
  on:
    branch: main
  target_branch: gh-pages
