language: rust
os: linux
dist: focal # 使用 Ubuntu 20.04，默认包含更高版本的 Ruby

cache:
  - cargo

rust:
  - stable

before_install:
  # 安装更高版本 Ruby（如果 focal 默认未满足要求）
  - rvm install 3.1.0
  - rvm use 3.1.0 --default
  # 手动安装特定版本的 dpl
  - gem install dpl -v 2.0.3.beta.4

before_script:
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/mdbook || cargo install mdbook)
  - cargo install-update -a

script:
  - cd ./book
  - mdbook build # 如果有自定义路径：mdbook build path/to/mybook && mdbook test path/to/mybook

deploy:
  provider: pages
  strategy: git
  cleanup: false
  github-token: $GITHUB_TOKEN
  local-dir: ./book/book # 指向 mdbook 默认生成的输出路径
  keep-history: false
  on:
    branch: main
  target_branch: gh-pages
