language: rust
os: linux
dist: Noble

cache:
  - cargo

rust:
  - stable

before_install:
  - rvm install 3.1.0
  - rvm use 3.1.0 --default
  - gem update --system
  - gem install bundler
  - gem uninstall uri -v '0.13.1' || true
  - gem install uri -v '1.0.1'
  - gem install dpl -v 2.0.3.beta.4

before_script:
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/mdbook || cargo install mdbook)
  - cargo install-update -a

script:
  - cd ./book
  - mdbook build # 如果有自定义路径：mdbook build path/to/mybook && mdbook test path/to/mybook

deploy:
  provider: pages
  strategy: git
  cleanup: false
  github-token: $GITHUB_TOKEN
  local-dir: ./target # 指向 mdbook 默认生成的输出路径
  keep-history: false
  on:
    branch: main
  target_branch: gh-pages
